version: '3'
services:
  vote-service:
    build:
      context: ./voteservice
      dockerfile: ../Dockerfile
    env_file:
      - commons.env
    depends_on:
      - stan
    ports:
      - 8080:9222
    restart: on-failure
  vote-processor:
    build: 
      context: ./voteprocessor
      dockerfile: ../Dockerfile
    env_file:
      - commons.env
    depends_on:
      - stan
    restart: on-failure
  stan:
    image: nats-streaming