version: '3'
services:
  traefik:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  election-service:
    build:
      context: ./election
      dockerfile: ../Dockerfile
    env_file:
      - commons.env
    depends_on:
      - mongo
      - fluentd
    labels:
      - "traefik.backend=election-service"
      - "traefik.frontend.rule=PathPrefix: /election"
      - "traefik.port=9223"
      - "traefik.frontend.entryPoints=http"
    restart: on-failure
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: election.access

  vote-service:
    build:
      context: ./voteservice
      dockerfile: ../Dockerfile
    env_file:
      - commons.env
    depends_on:
      - stan
      - mongo
      - fluentd
    labels:
      - "traefik.backend=vote-service"
      - "traefik.frontend.rule=PathPrefix: /vote"
      - "traefik.port=9222"
      - "traefik.frontend.entryPoints=http"
    restart: on-failure
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: vote-service.access

  vote-processor:
    build: 
      context: ./voteprocessor
      dockerfile: ../Dockerfile
    env_file:
      - commons.env
    depends_on:
      - stan
      - mongo
      - fluentd
    restart: on-failure
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: vote-processor.access

  stan:
    image: nats-streaming
    restart: on-failure

  mongo:
    image: mongo
    restart: on-failure

  fluentd:
    build: ./fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/conf:/fluentd/etc

  elasticsearch:
    image: elasticsearch

  kibana:
    image: kibana
    ports:
      - "5601:5601"
