version: '3'
services:
  election-service:
    build:
      context: ./election
      dockerfile: ../Dockerfile
    env_file:
      - commons.env
    depends_on:
      - mongo
    restart: on-failure
  vote-service:
    build:
      context: ./voteservice
      dockerfile: ../Dockerfile
    env_file:
      - commons.env
    depends_on:
      - stan
      - mongo
    ports:
      - 8080:9222
    restart: on-failure
  vote-processor:
    build: 
      context: ./voteprocessor
      dockerfile: ../Dockerfile
    env_file:
      - commons.env
    depends_on:
      - stan
      - mongo
    restart: on-failure
  stan:
    image: nats-streaming
    restart: on-failure
  mongo:
    image: mongo
    restart: on-failure