version: '3'
services:
  traefik:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  election-service:
    build:
      context: ./election
      dockerfile: ../Dockerfile
    env_file:
      - commons.env
    depends_on:
      - mongo
    labels:
      - "traefik.backend=election-service"
      - "traefik.frontend.rule=PathPrefix: /election"
      - "traefik.port=9223"
      - "traefik.frontend.entryPoints=http"
    restart: on-failure
  vote-service:
    build:
      context: ./voteservice
      dockerfile: ../Dockerfile
    env_file:
      - commons.env
    depends_on:
      - stan
      - mongo
    labels:
      - "traefik.backend=vote-service"
      - "traefik.frontend.rule=PathPrefix: /vote"
      - "traefik.port=9222"
      - "traefik.frontend.entryPoints=http"
    restart: on-failure
  vote-processor:
    build: 
      context: ./voteprocessor
      dockerfile: ../Dockerfile
    env_file:
      - commons.env
    depends_on:
      - stan
      - mongo
    restart: on-failure
  stan:
    image: nats-streaming
    restart: on-failure
  mongo:
    image: mongo
    restart: on-failure