// Code generated by protoc-gen-go. DO NOT EDIT.
// source: election.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Election struct {
	Id                   int32                `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Start                *timestamp.Timestamp `protobuf:"bytes,2,opt,name=Start,proto3" json:"Start,omitempty"`
	End                  *timestamp.Timestamp `protobuf:"bytes,3,opt,name=End,proto3" json:"End,omitempty"`
	Candidates           []string             `protobuf:"bytes,4,rep,name=Candidates,proto3" json:"Candidates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Election) Reset()         { *m = Election{} }
func (m *Election) String() string { return proto.CompactTextString(m) }
func (*Election) ProtoMessage()    {}
func (*Election) Descriptor() ([]byte, []int) {
	return fileDescriptor_election_5417da8271c4d494, []int{0}
}
func (m *Election) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Election.Unmarshal(m, b)
}
func (m *Election) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Election.Marshal(b, m, deterministic)
}
func (dst *Election) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Election.Merge(dst, src)
}
func (m *Election) XXX_Size() int {
	return xxx_messageInfo_Election.Size(m)
}
func (m *Election) XXX_DiscardUnknown() {
	xxx_messageInfo_Election.DiscardUnknown(m)
}

var xxx_messageInfo_Election proto.InternalMessageInfo

func (m *Election) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Election) GetStart() *timestamp.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Election) GetEnd() *timestamp.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *Election) GetCandidates() []string {
	if m != nil {
		return m.Candidates
	}
	return nil
}

func init() {
	proto.RegisterType((*Election)(nil), "Election")
}

func init() { proto.RegisterFile("election.proto", fileDescriptor_election_5417da8271c4d494) }

var fileDescriptor_election_5417da8271c4d494 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xcd, 0x49, 0x4d,
	0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0x92, 0x4f, 0xcf, 0xcf, 0x4f,
	0xcf, 0x49, 0xd5, 0x07, 0xf3, 0x92, 0x4a, 0xd3, 0xf4, 0x4b, 0x32, 0x73, 0x53, 0x8b, 0x4b, 0x12,
	0x73, 0x0b, 0x20, 0x0a, 0x94, 0x66, 0x31, 0x72, 0x71, 0xb8, 0x42, 0xf5, 0x08, 0xf1, 0x71, 0x31,
	0x79, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x31, 0x79, 0xa6, 0x08, 0x19, 0x70, 0xb1,
	0x06, 0x97, 0x24, 0x16, 0x95, 0x48, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x1b, 0x49, 0xe9, 0x41, 0x4c,
	0xd3, 0x83, 0x99, 0xa6, 0x17, 0x02, 0x33, 0x2d, 0x08, 0xa2, 0x50, 0x48, 0x87, 0x8b, 0xd9, 0x35,
	0x2f, 0x45, 0x82, 0x99, 0xa0, 0x7a, 0x90, 0x32, 0x21, 0x39, 0x2e, 0x2e, 0xe7, 0xc4, 0xbc, 0x94,
	0xcc, 0x94, 0xc4, 0x92, 0xd4, 0x62, 0x09, 0x16, 0x05, 0x66, 0x0d, 0xce, 0x20, 0x24, 0x11, 0x27,
	0x96, 0x28, 0xa6, 0x82, 0xa4, 0x24, 0x36, 0xb0, 0x76, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xdc, 0x90, 0x8d, 0x0d, 0xdc, 0x00, 0x00, 0x00,
}
